import logging
import os
import re
import uuid
from pathlib import Path

from app.config import settings
from app.core.context import AgentContext
from app.skills.base import Skill

logger = logging.getLogger(__name__)


# ── Markdown parsing ──────────────────────────────────────────────────────────

def _parse_blocks(content: str) -> list[dict]:
    """
    Parse Markdown content into typed blocks.
    Returns list of {"type": "h1"|"h2"|"h3"|"bullet"|"paragraph", "text": str}.
    """
    blocks = []
    for line in content.splitlines():
        line = line.rstrip()
        if line.startswith("### "):
            blocks.append({"type": "h3", "text": line[4:]})
        elif line.startswith("## "):
            blocks.append({"type": "h2", "text": line[3:]})
        elif line.startswith("# "):
            blocks.append({"type": "h1", "text": line[2:]})
        elif line.startswith("- ") or line.startswith("* "):
            blocks.append({"type": "bullet", "text": line[2:]})
        elif line:
            blocks.append({"type": "paragraph", "text": line})
    return blocks


def _strip_md(text: str) -> str:
    """Strip inline **bold**, *italic*, and `code` markers."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    return text


def _md_to_reportlab(text: str) -> str:
    """Convert inline **bold** and *italic* to reportlab XML markup."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    text = re.sub(r"`(.+?)`", r"<font name='Courier'>\1</font>", text)
    # Escape bare ampersands not part of markup
    text = re.sub(r"&(?!amp;|lt;|gt;|quot;|apos;|#)", "&amp;", text)
    return text


def _safe_name(title: str) -> str:
    """Sanitise a title for use in a filename (max 24 chars)."""
    return re.sub(r"[^\w\-]", "_", title)[:24].strip("_")


def _output_path(title: str, ext: str) -> str:
    Path(settings.temp_outputs_dir).mkdir(parents=True, exist_ok=True)
    return os.path.join(
        settings.temp_outputs_dir,
        f"{uuid.uuid4().hex[:8]}_{_safe_name(title)}.{ext}",
    )


# ── Generators ────────────────────────────────────────────────────────────────

def _generate_pptx(title: str, content: str) -> str:
    from pptx import Presentation  # type: ignore[import]
    from pptx.util import Pt       # type: ignore[import]

    prs = Presentation()

    # ── Title slide ──────────────────────────────────────────────────────────
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by SPEDA"

    # ── Group blocks into slides at each H2 boundary ─────────────────────────
    slides: list[dict] = []   # [{"title": str, "lines": list[str]}]
    current: dict | None = None

    for block in _parse_blocks(content):
        if block["type"] == "h2":
            if current is not None:
                slides.append(current)
            current = {"title": block["text"], "lines": []}
        elif current is not None:
            prefix = "• " if block["type"] == "bullet" else ""
            indent = "    " if block["type"] == "h3" else ""
            current["lines"].append(indent + prefix + _strip_md(block["text"]))

    if current is not None:
        slides.append(current)

    # ── Render content slides ─────────────────────────────────────────────────
    content_layout = prs.slide_layouts[1]
    for slide_data in slides:
        sl = prs.slides.add_slide(content_layout)
        sl.shapes.title.text = slide_data["title"]
        if len(sl.placeholders) > 1:
            tf = sl.placeholders[1].text_frame
            tf.clear()
            for i, line in enumerate(slide_data["lines"]):
                if i == 0:
                    tf.paragraphs[0].text = line
                else:
                    tf.add_paragraph().text = line

    path = _output_path(title, "pptx")
    prs.save(path)
    return path


def _generate_docx(title: str, content: str) -> str:
    from docx import Document  # type: ignore[import]

    doc = Document()
    doc.add_heading(title, level=0)

    for block in _parse_blocks(content):
        text = _strip_md(block["text"])
        if block["type"] == "h1":
            doc.add_heading(text, level=1)
        elif block["type"] == "h2":
            doc.add_heading(text, level=2)
        elif block["type"] == "h3":
            doc.add_heading(text, level=3)
        elif block["type"] == "bullet":
            doc.add_paragraph(text, style="List Bullet")
        else:
            doc.add_paragraph(text)

    path = _output_path(title, "docx")
    doc.save(path)
    return path


def _generate_pdf(title: str, content: str) -> str:
    from reportlab.lib.enums import TA_LEFT                    # type: ignore[import]
    from reportlab.lib.pagesizes import A4                     # type: ignore[import]
    from reportlab.lib.styles import getSampleStyleSheet       # type: ignore[import]
    from reportlab.lib.units import cm                         # type: ignore[import]
    from reportlab.platypus import (                           # type: ignore[import]
        Paragraph, SimpleDocTemplate, Spacer,
    )

    path = _output_path(title, "pdf")
    doc = SimpleDocTemplate(
        path,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(title, styles["Title"]))
    story.append(Spacer(1, 0.5 * cm))

    for block in _parse_blocks(content):
        text = _md_to_reportlab(block["text"])
        if block["type"] == "h1":
            story.append(Spacer(1, 0.3 * cm))
            story.append(Paragraph(text, styles["Heading1"]))
        elif block["type"] == "h2":
            story.append(Spacer(1, 0.25 * cm))
            story.append(Paragraph(text, styles["Heading2"]))
        elif block["type"] == "h3":
            story.append(Spacer(1, 0.15 * cm))
            story.append(Paragraph(text, styles["Heading3"]))
        elif block["type"] == "bullet":
            story.append(Paragraph(f"• {text}", styles["Normal"]))
        else:
            story.append(Paragraph(text, styles["Normal"]))
            story.append(Spacer(1, 0.1 * cm))

    doc.build(story)
    return path


# ── Skill ─────────────────────────────────────────────────────────────────────

_GENERATORS = {
    "pptx": _generate_pptx,
    "docx": _generate_docx,
    "pdf": _generate_pdf,
}

_REQUIRED_LIBS = {
    "pptx": "python-pptx",
    "docx": "python-docx",
    "pdf": "reportlab",
}


class DocumentsSkill(Skill):
    name = "generate_document"
    description = (
        "Generates a downloadable PPTX, DOCX, or PDF file. "
        "Use ONLY when the user explicitly says they want a file to save, download, print, or send — "
        "e.g. 'create a PDF report', 'make a PowerPoint', 'export as Word'. "
        "NEVER use for flowcharts, diagrams, charts, graphs, dashboards, visualisations, "
        "or any request to 'draw', 'show', 'visualise', or 'render' something — "
        "those are answered with an html or svg fenced code block, not this tool. "
        "Returns the absolute path to the generated file."
    )
    input_schema = {
        "type": "object",
        "properties": {
            "format": {
                "type": "string",
                "enum": ["pptx", "docx", "pdf"],
                "description": "Output file format.",
            },
            "title": {
                "type": "string",
                "description": "Document title (used as the cover title and filename base).",
            },
            "content": {
                "type": "string",
                "description": (
                    "Document body in Markdown. "
                    "For PPTX: use ## headings as slide separators — each H2 becomes a new slide. "
                    "For DOCX/PDF: use # H1 for sections, ## H2 for subsections, - for bullets."
                ),
            },
        },
        "required": ["format", "title", "content"],
    }

    async def execute(self, args: dict, context: AgentContext) -> str:
        fmt = args.get("format", "").lower()
        title = args.get("title", "Untitled")
        content = args.get("content", "")

        logger.info(
            "documents_execute",
            extra={
                "request_id": context.request_id,
                "format": fmt,
                "title": title,
            },
        )

        generator = _GENERATORS.get(fmt)
        if generator is None:
            return f"Unsupported format '{fmt}'. Supported: pptx, docx, pdf."

        try:
            path = generator(title, content)
            logger.info(
                "documents_generated",
                extra={
                    "request_id": context.request_id,
                    "path": path,
                    "format": fmt,
                },
            )
            return path
        except ImportError:
            lib = _REQUIRED_LIBS.get(fmt, "required library")
            return (
                f"Cannot generate {fmt.upper()}: '{lib}' is not installed. "
                f"Run: uv add {lib}"
            )
        except Exception as e:
            logger.error(
                "documents_error",
                extra={
                    "request_id": context.request_id,
                    "format": fmt,
                    "error": str(e),
                },
            )
            return f"Document generation failed: {e}"
