package com.speda.heartbreaker.designsystem

import com.speda.heartbreaker.designsystem.brand.AgentMarks
import com.speda.heartbreaker.designsystem.brand.Brands
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Geometry gate for the agent wordmarks. The path data in AgentMarks is
 * generated by tracing the source art, so it is never hand-reviewed — these
 * assertions are what stands between a bad trace and a blank logo on screen.
 *
 * The path strings are parsed HERE rather than through Compose's PathParser:
 * that delegates to android.graphics.Path, which is a stub under JVM unit
 * tests, so it would assert against zeroes and pass no matter what. This
 * parser reads the same M/L/C/Z subset the generator emits.
 *
 * If one fails after a re-trace, fix the trace; do not loosen the assertion.
 */
class AgentMarksTest {

    private data class Bounds(val minX: Float, val maxX: Float, val minY: Float, val maxY: Float) {
        val width get() = maxX - minX
        val height get() = maxY - minY
    }

    /** Walks the path data, returning every coordinate pair it declares. */
    private fun points(d: String): List<Pair<Float, Float>> {
        val out = mutableListOf<Pair<Float, Float>>()
        val commands = Regex("([MLCZ])([^MLCZ]*)").findAll(d)
        var sawMove = false
        for (m in commands) {
            val cmd = m.groupValues[1]
            val nums = Regex("-?\\d*\\.?\\d+").findAll(m.groupValues[2])
                .map { it.value.toFloat() }.toList()
            val expected = when (cmd) {
                "M", "L" -> 2
                "C" -> 6
                else -> 0
            }
            assertEquals("$cmd takes $expected args, got ${nums.size}", expected, nums.size)
            if (cmd == "M") sawMove = true
            for (i in nums.indices step 2) out.add(nums[i] to nums[i + 1])
        }
        assertTrue("path declares no subpath", sawMove)
        return out
    }

    private fun bounds(d: String): Bounds {
        val p = points(d)
        return Bounds(
            p.minOf { it.first }, p.maxOf { it.first },
            p.minOf { it.second }, p.maxOf { it.second },
        )
    }

    /** The generator emits only M/L/C/Z, every subpath closed. */
    @Test
    fun everyMarkIsWellFormed() {
        assertFalse("no marks were generated", AgentMarks.PATHS.isEmpty())
        for ((id, d) in AgentMarks.PATHS) {
            assertTrue("$id does not start with a moveto", d.startsWith("M"))
            assertTrue("$id does not end closed", d.endsWith("Z"))
            assertTrue("$id uses a command outside M/L/C/Z", Regex("^[MLCZ0-9 .,-]+$").matches(d))
            assertTrue("$id has too few points to be a shape", points(d).size >= 3)
        }
    }

    /** Marks are normalised to a centred 100x100 box. Bounds here include the
     *  off-curve control points, which bulge slightly past the on-curve
     *  extremes the generator normalised against — worst observed is centurion
     *  at -1.78, hence the 2.5 slack. This is a sanity gate on a bad trace, not
     *  a pixel assertion. */
    @Test
    fun everyMarkFillsTheViewBox() {
        for ((id, d) in AgentMarks.PATHS) {
            val b = bounds(d)
            assertTrue("$id starts left of the box: ${b.minX}", b.minX >= -2.5f)
            assertTrue("$id starts above the box: ${b.minY}", b.minY >= -2.5f)
            assertTrue("$id overflows right: ${b.maxX}", b.maxX <= 102.5f)
            assertTrue("$id overflows bottom: ${b.maxY}", b.maxY <= 102.5f)
            // The larger dimension is the one that got normalised to the box.
            assertEquals(
                "$id is not scaled to the box", 100f,
                maxOf(b.width, b.height), 2.5f,
            )
        }
    }

    /** Every mark belongs to a real agent, so the colour lookup always hits. */
    @Test
    fun everyMarkMapsToABrand() {
        for (id in AgentMarks.PATHS.keys) {
            assertTrue("$id is not a known brand", Brands.BRANDS.containsKey(id))
        }
    }

    /** Orion has no art yet — has() must say so rather than throwing. */
    @Test
    fun agentsWithoutArtReportFalse() {
        assertFalse(AgentMarks.has("orion"))
        assertFalse(AgentMarks.has("warroom"))
        assertTrue(AgentMarks.has("speda"))
    }
}
