# SPDX-FileCopyrightText: 2026 Ahmet Erol Bayrak
# SPDX-License-Identifier: AGPL-3.0-or-later

import asyncio
import contextlib
import json
import logging
import uuid

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.context import AgentContext
from app.core.dispatch import BG_COMMAND, bg_ack
from app.database import AsyncSessionLocal, get_db
from app.schemas.chat import ChatRequest, SteerRequest
from app.core.surface import annotate_last_user
from app.services.compaction import COMPACT_COMMAND, compact_ack, compact_now
from app.services.errors import friendly_provider_error

logger = logging.getLogger(__name__)
router = APIRouter(tags=["chat"])

# SSE keepalive. A detached run emits events only when the engine does, so a long
# silent tool call (a multi-minute scan, a slow model) sends zero bytes and an
# intermediary (Caddy, a NAT, a VPN) can idle-kill the socket even though the turn
# is healthy. Wrap the subscriber stream and inject a ':' comment line whenever the
# source is quiet for KEEPALIVE_S. Comment lines are ignored by the client's SSE
# parser — they cost nothing but keep the pipe warm.
#
# The inner generator is pumped by a task into a queue; the outer loop races the
# queue against a timeout. This is deliberate: racing the generator's __anext__ with
# asyncio.wait_for would CANCEL it on every timeout, and for turns.subscribe that
# runs its finally and drops the subscription. Pumping keeps the subscription alive;
# only a real client disconnect (this wrapper being aclosed) tears it down.
KEEPALIVE_S = 15.0

# Headers that tell every hop NOT to buffer the stream — otherwise a proxy holds
# chunks back and delivers them in a burst, which reads as "wait… wait… paragraph".
SSE_HEADERS = {"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}


async def _with_keepalive(inner, interval: float = KEEPALIVE_S):
    q: asyncio.Queue = asyncio.Queue()
    _END = object()

    async def _pump():
        try:
            async for item in inner:
                await q.put(item)
        finally:
            await q.put(_END)

    task = asyncio.create_task(_pump())
    try:
        while True:
            try:
                item = await asyncio.wait_for(q.get(), timeout=interval)
            except asyncio.TimeoutError:
                yield ": ping\n\n"
                continue
            if item is _END:
                break
            yield item
    finally:
        task.cancel()
        with contextlib.suppress(BaseException):
            await task


@router.get("/models")
async def list_models():
    """Models across all configured providers — the LLM layer owns the catalog."""
    from app.services.llm_client import available_models

    return await available_models()


@router.get("/welcome/{agent_id}")
async def welcome(agent_id: str, request: Request):
    """A short JARVIS-style welcome remark for the home screen, in the addressed
    agent's voice and drawn from the owner's memory. Cached per agent per
    part-of-day, generated by the cheapest model — returns {text: ""} on any
    failure so the client just keeps its static greeting."""
    from app.services.welcome import get_welcome

    text = await get_welcome(agent_id, request.app.state.profiles, request.app.state.welcome_cache)
    return {"text": text}


@router.get("/budget-mode")
async def get_budget_mode_endpoint():
    """Current budget-mode state (for the UI toggle)."""
    from app.core.runtime_state import get_budget_mode
    return {"budget_mode": get_budget_mode()}


@router.post("/budget-mode")
async def set_budget_mode_endpoint(body: dict):
    """Toggle budget mode. Body: {\"enabled\": true|false}. Persists across restarts."""
    from app.core.runtime_state import set_budget_mode
    enabled = bool(body.get("enabled", True))
    return {"budget_mode": set_budget_mode(enabled)}


@router.get("/sessions/{session_id}/messages")
async def get_messages(
    session_id: int,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import select, asc
    from app.models.message import Message
    from app.services.chat_history import rows_from_messages

    result = await db.execute(
        select(Message)
        .where(Message.session_id == session_id)
        .order_by(asc(Message.created_at))
    )
    return rows_from_messages(result.scalars().all())


@router.get("/sessions")
async def list_sessions(
    request: Request,
    agent_id: str = "speda",
    limit: int = 500,
    db: AsyncSession = Depends(get_db),
):
    # Agent-scoped: defaults to Speda so the existing UI is unchanged; pass
    # ?agent_id=… to list another agent's sessions once the UI addresses them.
    session_manager = request.app.state.session_manager
    sessions = await session_manager.list_sessions(
        db, user_id=1, agent_id=agent_id, limit=limit
    )
    return [
        {
            "id": s.id,
            "title": s.title,
            "started_at": s.started_at.isoformat(),
            # Running token spend for the session. NULL on every session that
            # predates the counter — reported as 0 rather than omitted so the
            # UI never has to special-case a missing field.
            "tokens_in": s.token_count_input or 0,
            "tokens_out": s.token_count_output or 0,
        }
        for s in sessions
    ]


@router.delete("/sessions/{session_id}")
async def delete_session(
    session_id: int,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import delete, update
    from app.models.session import Session
    from app.models.message import Message
    from app.models.message_embedding import MessageEmbedding
    from app.models.tool_call import ToolCall
    from app.models.agent import AgentRecord
    from app.models.background_job import BackgroundJob
    from app.models.memory import Memory
    from app.models.observation import Observation

    # Six other tables carry a foreign key to sessions.id (memory.py,
    # observation.py, background_job.py, agent.py, message_embedding.py,
    # tool_call.py) — none of that existed when this endpoint was first
    # written, and a plain DELETE FROM messages started failing FOREIGN KEY
    # constraint failed the moment tool_calls/message_embeddings picked up
    # rows, taking the whole request (and, with it, the worker) down.
    #
    # Two different kinds of reference, two different responses. Memory,
    # observations, background jobs, and an agent's "currently in" pointer
    # merely CITE this session for context — they are durable by design
    # (CLAUDE.md: a memory fact stops being current by acquiring a
    # valid_until, never by deletion) and survive with the reference
    # cleared. Message embeddings and tool-call audit rows exist BECAUSE
    # this session's messages do, so they are deleted outright, in
    # child-before-parent order so nothing downstream ever sees a dangling
    # message_id or session_id mid-transaction.
    await db.execute(
        update(AgentRecord).where(AgentRecord.current_session_id == session_id)
        .values(current_session_id=None)
    )
    await db.execute(
        update(BackgroundJob).where(BackgroundJob.session_id == session_id)
        .values(session_id=None)
    )
    await db.execute(
        update(Memory).where(Memory.source_session_id == session_id)
        .values(source_session_id=None)
    )
    await db.execute(
        update(Observation).where(Observation.session_id == session_id)
        .values(session_id=None)
    )
    await db.execute(delete(MessageEmbedding).where(MessageEmbedding.session_id == session_id))
    await db.execute(delete(ToolCall).where(ToolCall.session_id == session_id))
    await db.execute(delete(Message).where(Message.session_id == session_id))
    await db.execute(delete(Session).where(Session.id == session_id))
    await db.commit()
    return {"ok": True}


@router.patch("/sessions/{session_id}")
async def rename_session(
    session_id: int,
    body: dict,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import select
    from app.models.session import Session

    result = await db.execute(select(Session).where(Session.id == session_id))
    session = result.scalar_one_or_none()
    if session:
        session.title = body.get("title", session.title)
        await db.commit()
    return {"ok": True}


async def _run_chat(
    request: Request,
    agent_id: str,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession,
):
    """Shared chat handler. Both the bare /chat (Speda) and /chat/{agent_id}
    routes call through here — the only difference is which agent is addressed."""
    orchestrator = request.app.state.orchestrator
    session_manager = request.app.state.session_manager
    # Resolve the addressed agent; an unknown agent_id is a routing error.
    profile = request.app.state.profiles.get(agent_id)
    if profile is None:
        raise HTTPException(status_code=404, detail=f"Unknown agent '{agent_id}'")

    request_id = str(uuid.uuid4())
    user_id = 1

    # /bg <task> — background-dispatch THIS agent and return immediately,
    # skipping the whole orchestrator/external-proxy turn below. No other
    # agent's judgment call is in the loop: the owner is already authenticated
    # by the time a request reaches this router (X-API-Key, middleware/auth.py),
    # which is exactly the authority `dispatch_agent` normally borrows from
    # whichever agent calls it — here the owner IS the caller, so dispatching
    # to the agent this request addresses (`from_agent == to_agent`) is
    # correct, not a loop risk. The command, the reply text and the
    # success/refusal branch are shared with the Telegram gateway via
    # app.core.dispatch, so the two surfaces cannot drift.
    if body.message.strip().startswith(BG_COMMAND):
        task_text = body.message.strip()[len(BG_COMMAND):].strip()
        from app.schemas.sse import SSEEvent, SSEEventType

        session = await session_manager.get_or_create(
            db=db, user_id=user_id, triggered_by="user",
            model_used=body.model or profile.allocate_model("user"),
            agent_id=profile.agent_id, session_id=body.session_id,
        )
        # The command is the owner's turn in this conversation; the finished
        # report threads back into the same session (origin_session_id below),
        # which is how progress stays visible from the conversation it started in.
        await session_manager.save_message(db, session.id, "user", body.message)

        if not task_text:
            reply = f"Usage: {BG_COMMAND} <what to do>"
        else:
            dispatcher = request.app.state.dispatcher
            if dispatcher is None:
                reply = "Background dispatch isn't available."
            else:
                outcome = await dispatcher.spawn(
                    from_agent=profile.agent_id, to_agent=profile.agent_id,
                    task=task_text, user_id=user_id, request_id=request_id,
                    origin_session_id=session.id, allow_self=True,
                )
                reply = bg_ack(outcome)
        await session_manager.save_message(
            db, session.id, "assistant", [{"type": "text", "text": reply}])

        async def _ack():
            yield SSEEvent(type=SSEEventType.CHUNK, data=reply,
                          session_id=session.id, request_id=request_id).to_sse()
            yield SSEEvent(type=SSEEventType.DONE, data={},
                          session_id=session.id, request_id=request_id).to_sse()
        return StreamingResponse(_ack(), media_type="text/event-stream")

    # /compact — fold older turns into a rolling summary right now, ignoring
    # the token threshold, and reply with a visible confirmation instead of
    # the silent post-turn background pass (maybe_compact_session). Shared
    # with the Telegram gateway via app.services.compaction so the two
    # surfaces cannot drift.
    if body.message.strip() == COMPACT_COMMAND:
        from app.schemas.sse import SSEEvent, SSEEventType

        session = await session_manager.get_or_create(
            db=db, user_id=user_id, triggered_by="user",
            model_used=body.model or profile.allocate_model("user"),
            agent_id=profile.agent_id, session_id=body.session_id,
        )
        await session_manager.save_message(db, session.id, "user", body.message)

        bg_model = profile.background_model(body.model or profile.allocate_model("user"))
        outcome = await compact_now(session.id, request_id, bg_model)
        reply = compact_ack(outcome)

        await session_manager.save_message(
            db, session.id, "assistant", [{"type": "text", "text": reply}])

        async def _compact_ack():
            yield SSEEvent(type=SSEEventType.CHUNK, data=reply,
                          session_id=session.id, request_id=request_id).to_sse()
            yield SSEEvent(type=SSEEventType.DONE, data={},
                          session_id=session.id, request_id=request_id).to_sse()
        return StreamingResponse(_compact_ack(), media_type="text/event-stream")

    model = body.model or profile.allocate_model("user")
    system_prompt = body.system_prompt or ""

    session = await session_manager.get_or_create(
        db=db,
        user_id=user_id,
        triggered_by="user",
        model_used=model,
        agent_id=profile.agent_id,
        session_id=body.session_id,
    )

    # Regenerate / edit: truncate the stored history to the kept prefix BEFORE
    # anything else, so the model can't be re-fed its own previous answer.
    #   - edit:       drop the old user turn + its assistant reply, then resend
    #                 the edited prompt as a fresh user message.
    #   - regenerate: drop just the last assistant reply, then re-run on the
    #                 existing history WITHOUT appending a new user message.
    if body.keep_messages is not None:
        await session_manager.truncate(db, session.id, body.keep_messages)

    if body.regenerate:
        # No new user message — re-run on the existing (now-truncated) history,
        # which already ends with the user turn being regenerated.
        history = await session_manager.load_history(db, session.id)
    else:
        from app.services.attachments import build_user_content

        user_content = build_user_content(body.message, body.attachments, body.documents)

        # Save FIRST, then load history including the new message. load_history
        # stamps user messages from their DB created_at, so the prompt built this
        # turn is byte-identical to the prefix reconstructed on every future turn —
        # that identity is what keeps the conversation prompt-cache valid (see
        # SessionManager.stamp_user_content).
        await session_manager.save_message(db, session.id, "user", user_content)
        history = await session_manager.load_history(db, session.id)

    # Ambient client context (surface + platform + opt-in location) — stamped onto
    # the live turn's newest user message ONLY, never persisted. Mirrors how the
    # timestamp reaches the model (stamp_user_content): it decorates the uncached
    # tail, so the stored+reloaded history stays byte-stable and the cache holds.
    # The agent's own presentation note rides along, so the voice brief ends with
    # what presenting looks like for THIS agent rather than only the generic how.
    annotate_last_user(history, body.client_context, getattr(profile, "canvas_brief", ""))

    context = AgentContext(
        agent_id=profile.agent_id,
        user_id=user_id,
        session_id=session.id,
        request_id=request_id,
        triggered_by="user",
        trigger_payload={"message": body.message},
        output_mode="respond",
        model=model,
        system_prompt=system_prompt,
        conversation_history=history,
        db=db,
        timezone=settings.owner_timezone,
    )

    # Pre-populate active_servers from the session's loaded-toolset memory so
    # tools loaded via use_toolset on a prior turn stay in the tool array — no
    # repeated use_toolset calls, no cache-busting rewrites.
    context.extra["active_servers"] = session_manager.get_loaded_servers(session.id)
    # Same for individually resolved tools (tool_search): seed from the session
    # so a tool found earlier in the conversation is still callable, and give the
    # skill a callback to record new ones without handing it the SessionManager.
    context.extra["loaded_tools"] = session_manager.get_loaded_tools(session.id)
    context.extra["mark_tools_loaded"] = (
        lambda names, _sid=session.id: session_manager.mark_tools_loaded(_sid, names)
    )

    # Engine selection: an agent backed by a connected standalone peer (Optimus)
    # streams this turn through the external proxy instead of the in-process
    # orchestrator. Both yield the same SSEEvents, so persistence, background
    # tasks and the UI are identical either way; peer offline → normal path.
    # user_model carries the owner's EXPLICIT model pick (None = peer's choice).
    context.extra["user_model"] = body.model
    # Working directory for an external-backend agent (the Forge). The external
    # proxy forwards it as chat_request.cwd; in-process agents ignore it.
    if body.cwd:
        context.extra["cwd"] = body.cwd
    # Exact live coordinates for the navigation skills (get_route / find_places),
    # so they can default the origin without parsing the prose location line.
    # Not persisted — lives only on this turn's context, like the surface line.
    if body.client_context and body.client_context.location is not None:
        _loc = body.client_context.location
        context.extra["client_location"] = {
            "lat": _loc.lat, "lng": _loc.lng, "place": _loc.place,
        }
    # Which surface this turn came from, for the skills that are not available
    # on every client (house_party). Same discipline as the location above: a
    # per-turn fact on the context, never persisted onto the session.
    if body.client_context:
        context.extra["client_platform"] = body.client_context.platform
    use_external = (
        profile.external_backend
        and request.app.state.ws_manager.is_connected(profile.agent_id)
    )
    agent_proxy = request.app.state.agent_proxy

    def engine_factory(ctx: AgentContext):
        # Same SSEEvents either way, so persistence/UI are identical. The runner
        # sets ctx.db to its own session before calling this, so the engine and
        # persistence share one runner-owned session (never the request's).
        return agent_proxy.run(ctx) if use_external else orchestrator.run(ctx)

    def format_error(exc: Exception) -> str:
        return friendly_provider_error(model, exc)

    # Post-turn work (title/log/compaction/embedding) runs at turn COMPLETION —
    # detached from the response — so it fires even if the client disconnected
    # (fact 7). Same-provider model as the chat (never silently burns Anthropic
    # credit while chatting on OpenAI/Gemini).
    bg_model = profile.background_model(model)

    async def on_complete() -> None:
        from app.services.memory import run_post_turn_tasks
        await run_post_turn_tasks(session.id, request_id, user_id, bg_model)

    # Launch the turn DETACHED. The request's DB session (Depends) is only used
    # up to here (building history); the runner opens its own for the engine.
    started = request.app.state.turns.start(
        context=context,
        engine_factory=engine_factory,
        format_error=format_error,
        on_complete=on_complete,
    )
    if started is None:
        # Active-turn cap hit — surface a terminal error stream, no run launched.
        from app.schemas.sse import SSEEvent, SSEEventType

        async def _busy():
            yield SSEEvent(
                type=SSEEventType.ERROR,
                data="Too many turns are running at once. Wait for one to finish and retry.",
                session_id=session.id, request_id=request_id,
            ).to_sse()

        return StreamingResponse(_busy(), media_type="text/event-stream")

    # The response is just a SUBSCRIBER to the detached run. Dropping it (reload,
    # switch, watchdog) unsubscribes but never cancels — the run persists itself.
    return StreamingResponse(
        _with_keepalive(request.app.state.turns.subscribe(request_id)),
        media_type="text/event-stream",
        headers=SSE_HEADERS,
    )


@router.post("/chat")
async def chat(
    request: Request,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    """Bare /chat targets the default agent (Speda) — backward compatible with
    the desktop client."""
    return await _run_chat(request, "speda", body, background_tasks, db)


@router.post("/chat/{agent_id}")
async def chat_agent(
    agent_id: str,
    request: Request,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    """Address a specific in-process agent (e.g. /chat/ultron). 404 if unknown."""
    return await _run_chat(request, agent_id, body, background_tasks, db)


@router.get("/chat/active")
async def chat_active(request: Request, agent_id: str | None = None, session_id: int | None = None):
    """Detached turns currently running — optionally filtered by agent or session.
    The client polls this on entering a session to discover a live run it should
    re-attach to (BgOps Phase 3)."""
    return request.app.state.turns.active(agent_id=agent_id, session_id=session_id)


@router.get("/chat/attach/{request_id}")
async def chat_attach(request_id: str, request: Request):
    """Re-attach to a detached turn: replays the buffered events, then tails the
    live stream to completion. An unknown/evicted id yields an empty stream (its
    answer is already in the DB — the client just reloads the session normally)."""
    return StreamingResponse(
        _with_keepalive(request.app.state.turns.subscribe(request_id)),
        media_type="text/event-stream",
        headers=SSE_HEADERS,
    )


@router.post("/chat/cancel/{request_id}")
async def chat_cancel(request_id: str, request: Request):
    """Cancel a running turn (the stop button). Dropping the SSE socket no longer
    cancels anything, so this is the ONLY way to stop a run; the partial answer
    is persisted with a marker. Returns {cancelled: bool}."""
    ok = await request.app.state.turns.cancel(request_id)
    return {"cancelled": ok}


@router.post("/chat/steer/{request_id}")
async def chat_steer(request_id: str, body: SteerRequest, request: Request):
    """Inject a message into a running turn instead of starting a second one —
    the desktop counterpart of the Telegram gateway's steering (app/telegram/
    gateway.py). Only reaches an EXTERNAL turn: the inbox that claims it lives
    in the Forge engine (forge/warden/inbox.py), not the in-process
    orchestrator, so an in-process turn has nothing to steer into. `steered:
    false` means the composer should fall back to sending a normal message —
    the turn already ended, or was never external to begin with."""
    proxy = request.app.state.agent_proxy
    ok = await proxy.steer(request_id, body.text) if proxy is not None else False
    return {"steered": ok}


@router.websocket("/ws")
async def websocket_chat(websocket: WebSocket):
    await websocket.accept()

    orchestrator = websocket.app.state.orchestrator
    session_manager = websocket.app.state.session_manager
    # Real-time chat targets the default agent (Speda) for now.
    profile = websocket.app.state.profiles.default

    logger.info("ws_flutter_connect")

    try:
        while True:
            raw = await websocket.receive_text()

            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_text(
                    json.dumps({"type": "error", "data": "Invalid JSON"})
                )
                continue

            message = data.get("message", "").strip()
            session_id_req = data.get("session_id")

            if not message:
                continue

            request_id = str(uuid.uuid4())
            user_id = 1

            async with AsyncSessionLocal() as db:
                session = await session_manager.get_or_create(
                    db=db,
                    user_id=user_id,
                    triggered_by="user",
                    model_used=profile.allocate_model("user"),
                    agent_id=profile.agent_id,
                    session_id=session_id_req,
                )

                # Save first; load_history returns the new message already
                # timestamp-stamped from its DB created_at (cache-stable).
                await session_manager.save_message(db, session.id, "user", message)
                history = await session_manager.load_history(db, session.id)

                context = AgentContext(
                    agent_id=profile.agent_id,
                    user_id=user_id,
                    session_id=session.id,
                    request_id=request_id,
                    triggered_by="user",
                    trigger_payload={"message": message},
                    output_mode="respond",
                    model=profile.allocate_model("user"),
                    system_prompt="",
                    conversation_history=history,
                    db=db,
                    timezone=settings.owner_timezone,
                )

                collected_chunks: list[str] = []

                async for event in orchestrator.run(context):
                    if event.type.value == "chunk":
                        collected_chunks.append(str(event.data))
                    await websocket.send_text(event.to_json())

                full_response = "".join(collected_chunks)
                if full_response:
                    await session_manager.save_message(
                        db, session.id, "assistant", full_response
                    )

            # Same post-turn fan-out as the HTTP path (log, recap, daily
            # maintenance, title, compaction, embedding) — one canonical set.
            from app.services.memory import run_post_turn_tasks

            asyncio.create_task(
                run_post_turn_tasks(
                    session.id, request_id, user_id,
                    profile.background_model(profile.allocate_model("user")),
                )
            )

    except WebSocketDisconnect:
        logger.info("ws_flutter_disconnect")
    except Exception as e:
        logger.error("ws_error", extra={"error": str(e)})
        try:
            await websocket.send_text(json.dumps({"type": "error", "data": str(e)}))
        except Exception:
            pass
