import asyncio
import json
import logging
import uuid

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.context import AgentContext
from app.database import AsyncSessionLocal, get_db
from app.schemas.chat import ChatRequest
from app.core.surface import annotate_last_user
from app.services.errors import friendly_provider_error

logger = logging.getLogger(__name__)
router = APIRouter(tags=["chat"])


@router.get("/models")
async def list_models():
    """Models across all configured providers — the LLM layer owns the catalog."""
    from app.services.llm_client import available_models

    return await available_models()


@router.get("/welcome/{agent_id}")
async def welcome(agent_id: str, request: Request):
    """A short JARVIS-style welcome remark for the home screen, in the addressed
    agent's voice and drawn from the owner's memory. Cached per agent per
    part-of-day, generated by the cheapest model — returns {text: ""} on any
    failure so the client just keeps its static greeting."""
    from app.services.welcome import get_welcome

    text = await get_welcome(agent_id, request.app.state.profiles, request.app.state.welcome_cache)
    return {"text": text}


@router.get("/budget-mode")
async def get_budget_mode_endpoint():
    """Current budget-mode state (for the UI toggle)."""
    from app.core.runtime_state import get_budget_mode
    return {"budget_mode": get_budget_mode()}


@router.post("/budget-mode")
async def set_budget_mode_endpoint(body: dict):
    """Toggle budget mode. Body: {\"enabled\": true|false}. Persists across restarts."""
    from app.core.runtime_state import set_budget_mode
    enabled = bool(body.get("enabled", True))
    return {"budget_mode": set_budget_mode(enabled)}


@router.get("/sessions/{session_id}/messages")
async def get_messages(
    session_id: int,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import select, asc
    from app.models.message import Message
    from app.services.chat_history import rows_from_messages

    result = await db.execute(
        select(Message)
        .where(Message.session_id == session_id)
        .order_by(asc(Message.created_at))
    )
    return rows_from_messages(result.scalars().all())


@router.get("/sessions")
async def list_sessions(
    request: Request,
    agent_id: str = "speda",
    limit: int = 500,
    db: AsyncSession = Depends(get_db),
):
    # Agent-scoped: defaults to SPEDA so the existing UI is unchanged; pass
    # ?agent_id=… to list another agent's sessions once the UI addresses them.
    session_manager = request.app.state.session_manager
    sessions = await session_manager.list_sessions(
        db, user_id=1, agent_id=agent_id, limit=limit
    )
    return [
        {"id": s.id, "title": s.title, "started_at": s.started_at.isoformat()}
        for s in sessions
    ]


@router.delete("/sessions/{session_id}")
async def delete_session(
    session_id: int,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import delete
    from app.models.session import Session
    from app.models.message import Message

    await db.execute(delete(Message).where(Message.session_id == session_id))
    await db.execute(delete(Session).where(Session.id == session_id))
    await db.commit()
    return {"ok": True}


@router.patch("/sessions/{session_id}")
async def rename_session(
    session_id: int,
    body: dict,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import select
    from app.models.session import Session

    result = await db.execute(select(Session).where(Session.id == session_id))
    session = result.scalar_one_or_none()
    if session:
        session.title = body.get("title", session.title)
        await db.commit()
    return {"ok": True}


async def _run_chat(
    request: Request,
    agent_id: str,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession,
):
    """Shared chat handler. Both the bare /chat (SPEDA) and /chat/{agent_id}
    routes call through here — the only difference is which agent is addressed."""
    orchestrator = request.app.state.orchestrator
    session_manager = request.app.state.session_manager
    # Resolve the addressed agent; an unknown agent_id is a routing error.
    profile = request.app.state.profiles.get(agent_id)
    if profile is None:
        raise HTTPException(status_code=404, detail=f"Unknown agent '{agent_id}'")

    request_id = str(uuid.uuid4())
    user_id = 1

    model = body.model or profile.allocate_model("user")
    system_prompt = body.system_prompt or ""

    session = await session_manager.get_or_create(
        db=db,
        user_id=user_id,
        triggered_by="user",
        model_used=model,
        agent_id=profile.agent_id,
        session_id=body.session_id,
    )

    # Regenerate / edit: truncate the stored history to the kept prefix BEFORE
    # anything else, so the model can't be re-fed its own previous answer.
    #   - edit:       drop the old user turn + its assistant reply, then resend
    #                 the edited prompt as a fresh user message.
    #   - regenerate: drop just the last assistant reply, then re-run on the
    #                 existing history WITHOUT appending a new user message.
    if body.keep_messages is not None:
        await session_manager.truncate(db, session.id, body.keep_messages)

    if body.regenerate:
        # No new user message — re-run on the existing (now-truncated) history,
        # which already ends with the user turn being regenerated.
        history = await session_manager.load_history(db, session.id)
    else:
        from app.services.attachments import build_user_content

        user_content = build_user_content(body.message, body.attachments, body.documents)

        # Save FIRST, then load history including the new message. load_history
        # stamps user messages from their DB created_at, so the prompt built this
        # turn is byte-identical to the prefix reconstructed on every future turn —
        # that identity is what keeps the conversation prompt-cache valid (see
        # SessionManager.stamp_user_content).
        await session_manager.save_message(db, session.id, "user", user_content)
        history = await session_manager.load_history(db, session.id)

    # Ambient client context (surface + platform + opt-in location) — stamped onto
    # the live turn's newest user message ONLY, never persisted. Mirrors how the
    # timestamp reaches the model (stamp_user_content): it decorates the uncached
    # tail, so the stored+reloaded history stays byte-stable and the cache holds.
    annotate_last_user(history, body.client_context)

    context = AgentContext(
        agent_id=profile.agent_id,
        user_id=user_id,
        session_id=session.id,
        request_id=request_id,
        triggered_by="user",
        trigger_payload={"message": body.message},
        output_mode="respond",
        model=model,
        system_prompt=system_prompt,
        conversation_history=history,
        db=db,
        timezone=settings.owner_timezone,
    )

    # Pre-populate active_servers from the session's loaded-toolset memory so
    # tools loaded via use_toolset on a prior turn stay in the tool array — no
    # repeated use_toolset calls, no cache-busting rewrites.
    context.extra["active_servers"] = session_manager.get_loaded_servers(session.id)

    # Engine selection: an agent backed by a connected standalone peer (Optimus)
    # streams this turn through the external proxy instead of the in-process
    # orchestrator. Both yield the same SSEEvents, so persistence, background
    # tasks and the UI are identical either way; peer offline → normal path.
    # user_model carries the owner's EXPLICIT model pick (None = peer's choice).
    context.extra["user_model"] = body.model
    # Working directory for an external-backend agent (the Forge). The external
    # proxy forwards it as chat_request.cwd; in-process agents ignore it.
    if body.cwd:
        context.extra["cwd"] = body.cwd
    # Exact live coordinates for the navigation skills (get_route / find_places),
    # so they can default the origin without parsing the prose location line.
    # Not persisted — lives only on this turn's context, like the surface line.
    if body.client_context and body.client_context.location is not None:
        _loc = body.client_context.location
        context.extra["client_location"] = {
            "lat": _loc.lat, "lng": _loc.lng, "place": _loc.place,
        }
    use_external = (
        profile.external_backend
        and request.app.state.ws_manager.is_connected(profile.agent_id)
    )
    agent_proxy = request.app.state.agent_proxy

    def engine_factory(ctx: AgentContext):
        # Same SSEEvents either way, so persistence/UI are identical. The runner
        # sets ctx.db to its own session before calling this, so the engine and
        # persistence share one runner-owned session (never the request's).
        return agent_proxy.run(ctx) if use_external else orchestrator.run(ctx)

    def format_error(exc: Exception) -> str:
        return friendly_provider_error(model, exc)

    # Post-turn work (title/log/compaction/embedding) runs at turn COMPLETION —
    # detached from the response — so it fires even if the client disconnected
    # (fact 7). Same-provider model as the chat (never silently burns Anthropic
    # credit while chatting on OpenAI/Gemini).
    bg_model = profile.background_model(model)

    async def on_complete() -> None:
        from app.services.memory import run_post_turn_tasks
        await run_post_turn_tasks(session.id, request_id, user_id, bg_model)

    # Launch the turn DETACHED. The request's DB session (Depends) is only used
    # up to here (building history); the runner opens its own for the engine.
    started = request.app.state.turns.start(
        context=context,
        engine_factory=engine_factory,
        format_error=format_error,
        on_complete=on_complete,
    )
    if started is None:
        # Active-turn cap hit — surface a terminal error stream, no run launched.
        from app.schemas.sse import SSEEvent, SSEEventType

        async def _busy():
            yield SSEEvent(
                type=SSEEventType.ERROR,
                data="Too many turns are running at once. Wait for one to finish and retry.",
                session_id=session.id, request_id=request_id,
            ).to_sse()

        return StreamingResponse(_busy(), media_type="text/event-stream")

    # The response is just a SUBSCRIBER to the detached run. Dropping it (reload,
    # switch, watchdog) unsubscribes but never cancels — the run persists itself.
    return StreamingResponse(
        request.app.state.turns.subscribe(request_id),
        media_type="text/event-stream",
    )


@router.post("/chat")
async def chat(
    request: Request,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    """Bare /chat targets the default agent (SPEDA) — backward compatible with
    the desktop client."""
    return await _run_chat(request, "speda", body, background_tasks, db)


@router.post("/chat/{agent_id}")
async def chat_agent(
    agent_id: str,
    request: Request,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    """Address a specific in-process agent (e.g. /chat/ultron). 404 if unknown."""
    return await _run_chat(request, agent_id, body, background_tasks, db)


@router.get("/chat/active")
async def chat_active(request: Request, agent_id: str | None = None, session_id: int | None = None):
    """Detached turns currently running — optionally filtered by agent or session.
    The client polls this on entering a session to discover a live run it should
    re-attach to (BgOps Phase 3)."""
    return request.app.state.turns.active(agent_id=agent_id, session_id=session_id)


@router.get("/chat/attach/{request_id}")
async def chat_attach(request_id: str, request: Request):
    """Re-attach to a detached turn: replays the buffered events, then tails the
    live stream to completion. An unknown/evicted id yields an empty stream (its
    answer is already in the DB — the client just reloads the session normally)."""
    return StreamingResponse(
        request.app.state.turns.subscribe(request_id),
        media_type="text/event-stream",
    )


@router.post("/chat/cancel/{request_id}")
async def chat_cancel(request_id: str, request: Request):
    """Cancel a running turn (the stop button). Dropping the SSE socket no longer
    cancels anything, so this is the ONLY way to stop a run; the partial answer
    is persisted with a marker. Returns {cancelled: bool}."""
    ok = await request.app.state.turns.cancel(request_id)
    return {"cancelled": ok}


@router.websocket("/ws")
async def websocket_chat(websocket: WebSocket):
    await websocket.accept()

    orchestrator = websocket.app.state.orchestrator
    session_manager = websocket.app.state.session_manager
    # Real-time chat targets the default agent (SPEDA) for now.
    profile = websocket.app.state.profiles.default

    logger.info("ws_flutter_connect")

    try:
        while True:
            raw = await websocket.receive_text()

            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_text(
                    json.dumps({"type": "error", "data": "Invalid JSON"})
                )
                continue

            message = data.get("message", "").strip()
            session_id_req = data.get("session_id")

            if not message:
                continue

            request_id = str(uuid.uuid4())
            user_id = 1

            async with AsyncSessionLocal() as db:
                session = await session_manager.get_or_create(
                    db=db,
                    user_id=user_id,
                    triggered_by="user",
                    model_used=profile.allocate_model("user"),
                    agent_id=profile.agent_id,
                    session_id=session_id_req,
                )

                # Save first; load_history returns the new message already
                # timestamp-stamped from its DB created_at (cache-stable).
                await session_manager.save_message(db, session.id, "user", message)
                history = await session_manager.load_history(db, session.id)

                context = AgentContext(
                    agent_id=profile.agent_id,
                    user_id=user_id,
                    session_id=session.id,
                    request_id=request_id,
                    triggered_by="user",
                    trigger_payload={"message": message},
                    output_mode="respond",
                    model=profile.allocate_model("user"),
                    system_prompt="",
                    conversation_history=history,
                    db=db,
                    timezone=settings.owner_timezone,
                )

                collected_chunks: list[str] = []

                async for event in orchestrator.run(context):
                    if event.type.value == "chunk":
                        collected_chunks.append(str(event.data))
                    await websocket.send_text(event.to_json())

                full_response = "".join(collected_chunks)
                if full_response:
                    await session_manager.save_message(
                        db, session.id, "assistant", full_response
                    )

            # Same post-turn fan-out as the HTTP path (log, recap, daily
            # maintenance, title, compaction, embedding) — one canonical set.
            from app.services.memory import run_post_turn_tasks

            asyncio.create_task(
                run_post_turn_tasks(
                    session.id, request_id, user_id,
                    profile.background_model(profile.allocate_model("user")),
                )
            )

    except WebSocketDisconnect:
        logger.info("ws_flutter_disconnect")
    except Exception as e:
        logger.error("ws_error", extra={"error": str(e)})
        try:
            await websocket.send_text(json.dumps({"type": "error", "data": str(e)}))
        except Exception:
            pass
