import asyncio
import json
import logging
import uuid

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.context import AgentContext
from app.database import AsyncSessionLocal, get_db
from app.schemas.chat import ChatRequest

logger = logging.getLogger(__name__)
router = APIRouter(tags=["chat"])


def _friendly_error(model: str, exc: Exception) -> str:
    """Turn a raw provider exception into a short, actionable message for the UI.
    Covers the common dead-ends (missing key, no credit, rate limit, no uplink)
    across every provider so the user sees WHY instead of a frozen spinner."""
    provider = model.partition(":")[0] if ":" in model else "anthropic"
    text = str(exc).lower()
    if "401" in text or "unauthorized" in text or "api key" in text or "authentication" in text:
        key = {"openai": "OPENAI_API_KEY", "gemini": "GEMINI_API_KEY"}.get(provider, "ANTHROPIC_API_KEY")
        return f"{provider.title()} rejected the request — check that {key} is set and valid."
    if "credit" in text or "billing" in text or "quota" in text or "insufficient" in text:
        return f"{provider.title()} reports no available credit/quota for this account."
    if "429" in text or "rate limit" in text or "overloaded" in text or "529" in text:
        return f"{provider.title()} is rate-limited or overloaded right now — try again shortly."
    if "connect" in text or "timeout" in text or "connection" in text:
        return f"Couldn't reach {provider.title()}. Check the network (or the local Ollama daemon)."
    return f"{provider.title()} request failed: {exc}"

@router.get("/models")
async def list_models():
    """Models across all configured providers — the LLM layer owns the catalog."""
    from app.services.llm_client import available_models

    return await available_models()


@router.get("/welcome/{agent_id}")
async def welcome(agent_id: str, request: Request):
    """A short JARVIS-style welcome remark for the home screen, in the addressed
    agent's voice and drawn from the owner's memory. Cached per agent per
    part-of-day, generated by the cheapest model — returns {text: ""} on any
    failure so the client just keeps its static greeting."""
    from app.services.welcome import get_welcome

    text = await get_welcome(agent_id, request.app.state.profiles)
    return {"text": text}


@router.get("/budget-mode")
async def get_budget_mode_endpoint():
    """Current budget-mode state (for the UI toggle)."""
    from app.core.runtime_state import get_budget_mode
    return {"budget_mode": get_budget_mode()}


@router.post("/budget-mode")
async def set_budget_mode_endpoint(body: dict):
    """Toggle budget mode. Body: {\"enabled\": true|false}. Persists across restarts."""
    from app.core.runtime_state import set_budget_mode
    enabled = bool(body.get("enabled", True))
    return {"budget_mode": set_budget_mode(enabled)}


@router.get("/sessions/{session_id}/messages")
async def get_messages(
    session_id: int,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import select, asc
    from app.models.message import Message

    result = await db.execute(
        select(Message)
        .where(Message.session_id == session_id)
        .order_by(asc(Message.created_at))
    )
    messages = result.scalars().all()

    def extract_text(content) -> str:
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            return ''.join(
                block.get('text', '') for block in content
                if isinstance(block, dict) and block.get('type') == 'text'
            )
        return ''

    def extract_images(content) -> list[str]:
        """Rebuild data: URLs from stored base64 image blocks so attachments
        re-render when an old session is reopened (they're persisted in the DB)."""
        if not isinstance(content, list):
            return []
        out = []
        for block in content:
            if isinstance(block, dict) and block.get('type') == 'image':
                src = block.get('source', {})
                if src.get('type') == 'base64' and src.get('data'):
                    out.append(f"data:{src.get('media_type', 'image/png')};base64,{src['data']}")
        return out

    def extract_meta(content) -> dict:
        """Pull the SPEDA display-only meta block so the tool disclosure,
        download cards (assistant) and upload chips (user) survive a reload."""
        if not isinstance(content, list):
            return {}
        for block in content:
            if isinstance(block, dict) and block.get('type') == '_speda_meta':
                return {
                    'tools': block.get('tools', []),
                    'files': block.get('files', []),
                    'uploads': block.get('uploads', []),
                }
        return {}

    out = []
    for m in messages:
        if m.role not in ('user', 'assistant'):
            continue
        meta = extract_meta(m.content)
        # For a user turn with document uploads, the real text blocks hold the
        # extracted file contents; the bubble must show only the user's own
        # message, which was stashed in the meta block at save time.
        if m.role == 'user' and meta.get('uploads'):
            content_text = meta.get('text', '')
        else:
            content_text = extract_text(m.content)
        row = {
            'id': str(m.id),
            'role': m.role,
            'content': content_text,
            'tools': meta.get('tools', []),
            'isStreaming': False,
            'isError': False,
        }
        if (imgs := extract_images(m.content)):
            row['images'] = imgs
        if meta.get('files'):
            row['files'] = meta['files']
        if meta.get('uploads'):
            row['uploads'] = meta['uploads']
        out.append(row)
    return out


@router.get("/sessions")
async def list_sessions(
    request: Request,
    agent_id: str = "speda",
    limit: int = 500,
    db: AsyncSession = Depends(get_db),
):
    # Agent-scoped: defaults to SPEDA so the existing UI is unchanged; pass
    # ?agent_id=… to list another agent's sessions once the UI addresses them.
    session_manager = request.app.state.session_manager
    sessions = await session_manager.list_sessions(
        db, user_id=1, agent_id=agent_id, limit=limit
    )
    return [
        {"id": s.id, "title": s.title, "started_at": s.started_at.isoformat()}
        for s in sessions
    ]


@router.delete("/sessions/{session_id}")
async def delete_session(
    session_id: int,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import delete
    from app.models.session import Session
    from app.models.message import Message

    await db.execute(delete(Message).where(Message.session_id == session_id))
    await db.execute(delete(Session).where(Session.id == session_id))
    await db.commit()
    return {"ok": True}


@router.patch("/sessions/{session_id}")
async def rename_session(
    session_id: int,
    body: dict,
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import select
    from app.models.session import Session

    result = await db.execute(select(Session).where(Session.id == session_id))
    session = result.scalar_one_or_none()
    if session:
        session.title = body.get("title", session.title)
        await db.commit()
    return {"ok": True}


async def _run_chat(
    request: Request,
    agent_id: str,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession,
):
    """Shared chat handler. Both the bare /chat (SPEDA) and /chat/{agent_id}
    routes call through here — the only difference is which agent is addressed."""
    orchestrator = request.app.state.orchestrator
    session_manager = request.app.state.session_manager
    # Resolve the addressed agent; an unknown agent_id is a routing error.
    profile = request.app.state.profiles.get(agent_id)
    if profile is None:
        raise HTTPException(status_code=404, detail=f"Unknown agent '{agent_id}'")

    request_id = str(uuid.uuid4())
    user_id = 1

    model = body.model or profile.allocate_model("user")
    system_prompt = body.system_prompt or ""

    session = await session_manager.get_or_create(
        db=db,
        user_id=user_id,
        triggered_by="user",
        model_used=model,
        agent_id=profile.agent_id,
        session_id=body.session_id,
    )

    # Regenerate / edit: truncate the stored history to the kept prefix BEFORE
    # anything else, so the model can't be re-fed its own previous answer.
    #   - edit:       drop the old user turn + its assistant reply, then resend
    #                 the edited prompt as a fresh user message.
    #   - regenerate: drop just the last assistant reply, then re-run on the
    #                 existing history WITHOUT appending a new user message.
    if body.keep_messages is not None:
        await session_manager.truncate(db, session.id, body.keep_messages)

    if body.regenerate:
        # No new user message — re-run on the existing (now-truncated) history,
        # which already ends with the user turn being regenerated.
        history = await session_manager.load_history(db, session.id)
    else:
        # Build the user turn. Images keep their native vision blocks (every
        # provider's translation layer supports them). Non-image files are
        # extracted to plain text server-side and embedded as text blocks, so a
        # PDF/DOCX/XLSX/CSV reaches the model IDENTICALLY on every provider —
        # including open-weight and local ones that have no document support.
        if body.attachments or body.documents:
            from app.services.attachments import extract_text

            blocks: list = [
                {
                    "type": "image",
                    "source": {"type": "base64", "media_type": att.media_type, "data": att.data},
                }
                for att in body.attachments
            ]
            for doc in body.documents:
                blocks.append({"type": "text", "text": extract_text(doc.name, doc.media_type, doc.data)})
            if body.message:
                blocks.append({"type": "text", "text": body.message})
            # Display-only meta: upload chips on the user bubble survive a reload.
            # Stripped from the history sent to the model by SessionManager._clean.
            if body.documents:
                # `text` carries the user's own message so the reloaded bubble
                # shows it — NOT the wall of extracted document text (which lives
                # in real text blocks the model reads but the UI must not echo).
                blocks.append({
                    "type": "_speda_meta",
                    "uploads": [{"name": d.name, "size": d.size or 0} for d in body.documents],
                    "text": body.message or "",
                })
            user_content: list | str = blocks
        else:
            user_content = body.message

        # Save FIRST, then load history including the new message. load_history
        # stamps user messages from their DB created_at, so the prompt built this
        # turn is byte-identical to the prefix reconstructed on every future turn —
        # that identity is what keeps the conversation prompt-cache valid (see
        # SessionManager.stamp_user_content).
        await session_manager.save_message(db, session.id, "user", user_content)
        history = await session_manager.load_history(db, session.id)

    context = AgentContext(
        agent_id=profile.agent_id,
        user_id=user_id,
        session_id=session.id,
        request_id=request_id,
        triggered_by="user",
        trigger_payload={"message": body.message},
        output_mode="respond",
        model=model,
        system_prompt=system_prompt,
        conversation_history=history,
        db=db,
        timezone=settings.owner_timezone,
    )

    # Pre-populate active_servers from the session's loaded-toolset memory so
    # tools loaded via use_toolset on a prior turn stay in the tool array — no
    # repeated use_toolset calls, no cache-busting rewrites.
    context.extra["active_servers"] = session_manager.get_loaded_servers(session.id)

    # Engine selection: an agent backed by a connected standalone peer (Optimus)
    # streams this turn through the external proxy instead of the in-process
    # orchestrator. Both yield the same SSEEvents, so persistence, background
    # tasks and the UI are identical either way; peer offline → normal path.
    # user_model carries the owner's EXPLICIT model pick (None = peer's choice).
    context.extra["user_model"] = body.model
    # Working directory for an external-backend agent (the Forge). The external
    # proxy forwards it as chat_request.cwd; in-process agents ignore it.
    if body.cwd:
        context.extra["cwd"] = body.cwd
    use_external = (
        profile.external_backend
        and request.app.state.ws_manager.is_connected(profile.agent_id)
    )
    agent_proxy = request.app.state.agent_proxy

    def engine_factory(ctx: AgentContext):
        # Same SSEEvents either way, so persistence/UI are identical. The runner
        # sets ctx.db to its own session before calling this, so the engine and
        # persistence share one runner-owned session (never the request's).
        return agent_proxy.run(ctx) if use_external else orchestrator.run(ctx)

    def format_error(exc: Exception) -> str:
        return _friendly_error(model, exc)

    # Post-turn work (title/log/compaction/embedding) runs at turn COMPLETION —
    # detached from the response — so it fires even if the client disconnected
    # (fact 7). Same-provider model as the chat (never silently burns Anthropic
    # credit while chatting on OpenAI/Gemini).
    bg_model = profile.background_model(model)

    async def on_complete() -> None:
        from app.services.memory import run_post_turn_tasks
        await run_post_turn_tasks(session.id, request_id, user_id, bg_model)

    # Launch the turn DETACHED. The request's DB session (Depends) is only used
    # up to here (building history); the runner opens its own for the engine.
    started = request.app.state.turns.start(
        context=context,
        engine_factory=engine_factory,
        format_error=format_error,
        on_complete=on_complete,
    )
    if started is None:
        # Active-turn cap hit — surface a terminal error stream, no run launched.
        from app.schemas.sse import SSEEvent, SSEEventType

        async def _busy():
            yield SSEEvent(
                type=SSEEventType.ERROR,
                data="Too many turns are running at once. Wait for one to finish and retry.",
                session_id=session.id, request_id=request_id,
            ).to_sse()

        return StreamingResponse(_busy(), media_type="text/event-stream")

    # The response is just a SUBSCRIBER to the detached run. Dropping it (reload,
    # switch, watchdog) unsubscribes but never cancels — the run persists itself.
    return StreamingResponse(
        request.app.state.turns.subscribe(request_id),
        media_type="text/event-stream",
    )


@router.post("/chat")
async def chat(
    request: Request,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    """Bare /chat targets the default agent (SPEDA) — backward compatible with
    the desktop client."""
    return await _run_chat(request, "speda", body, background_tasks, db)


@router.post("/chat/{agent_id}")
async def chat_agent(
    agent_id: str,
    request: Request,
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
):
    """Address a specific in-process agent (e.g. /chat/ultron). 404 if unknown."""
    return await _run_chat(request, agent_id, body, background_tasks, db)


@router.get("/chat/active")
async def chat_active(request: Request, agent_id: str | None = None, session_id: int | None = None):
    """Detached turns currently running — optionally filtered by agent or session.
    The client polls this on entering a session to discover a live run it should
    re-attach to (BgOps Phase 3)."""
    return request.app.state.turns.active(agent_id=agent_id, session_id=session_id)


@router.get("/chat/attach/{request_id}")
async def chat_attach(request_id: str, request: Request):
    """Re-attach to a detached turn: replays the buffered events, then tails the
    live stream to completion. An unknown/evicted id yields an empty stream (its
    answer is already in the DB — the client just reloads the session normally)."""
    return StreamingResponse(
        request.app.state.turns.subscribe(request_id),
        media_type="text/event-stream",
    )


@router.post("/chat/cancel/{request_id}")
async def chat_cancel(request_id: str, request: Request):
    """Cancel a running turn (the stop button). Dropping the SSE socket no longer
    cancels anything, so this is the ONLY way to stop a run; the partial answer
    is persisted with a marker. Returns {cancelled: bool}."""
    ok = await request.app.state.turns.cancel(request_id)
    return {"cancelled": ok}


@router.websocket("/ws")
async def websocket_chat(websocket: WebSocket):
    await websocket.accept()

    orchestrator = websocket.app.state.orchestrator
    session_manager = websocket.app.state.session_manager
    # Real-time chat targets the default agent (SPEDA) for now.
    profile = websocket.app.state.profiles.default

    logger.info("ws_flutter_connect")

    try:
        while True:
            raw = await websocket.receive_text()

            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_text(
                    json.dumps({"type": "error", "data": "Invalid JSON"})
                )
                continue

            message = data.get("message", "").strip()
            session_id_req = data.get("session_id")

            if not message:
                continue

            request_id = str(uuid.uuid4())
            user_id = 1

            async with AsyncSessionLocal() as db:
                session = await session_manager.get_or_create(
                    db=db,
                    user_id=user_id,
                    triggered_by="user",
                    model_used=profile.allocate_model("user"),
                    agent_id=profile.agent_id,
                    session_id=session_id_req,
                )

                # Save first; load_history returns the new message already
                # timestamp-stamped from its DB created_at (cache-stable).
                await session_manager.save_message(db, session.id, "user", message)
                history = await session_manager.load_history(db, session.id)

                context = AgentContext(
                    agent_id=profile.agent_id,
                    user_id=user_id,
                    session_id=session.id,
                    request_id=request_id,
                    triggered_by="user",
                    trigger_payload={"message": message},
                    output_mode="respond",
                    model=profile.allocate_model("user"),
                    system_prompt="",
                    conversation_history=history,
                    db=db,
                    timezone=settings.owner_timezone,
                )

                collected_chunks: list[str] = []

                async for event in orchestrator.run(context):
                    if event.type.value == "chunk":
                        collected_chunks.append(str(event.data))
                    await websocket.send_text(event.to_json())

                full_response = "".join(collected_chunks)
                if full_response:
                    await session_manager.save_message(
                        db, session.id, "assistant", full_response
                    )

            # Same post-turn fan-out as the HTTP path (log, recap, daily
            # maintenance, title, compaction, embedding) — one canonical set.
            from app.services.memory import run_post_turn_tasks

            asyncio.create_task(
                run_post_turn_tasks(
                    session.id, request_id, user_id,
                    profile.background_model(profile.allocate_model("user")),
                )
            )

    except WebSocketDisconnect:
        logger.info("ws_flutter_disconnect")
    except Exception as e:
        logger.error("ws_error", extra={"error": str(e)})
        try:
            await websocket.send_text(json.dumps({"type": "error", "data": str(e)}))
        except Exception:
            pass
